### ISSUE TITLE
Laravel Pagination

### ISSUE THREAD

**Issue by joeljerushan** [OneWayTech/vue2-datatable#129]
Is it possible to Paginate Laravel Paginate feature with vue2-datatable ? my return view like following i would like to paginate this with this plugin ..

```js
{
  "current_page": 1,
  "data": [
  {
    "id": 1,
    "bill": "62753",
    "type": 3,
    "amount": 58,
    "price": 107,
    "date": "2018-06-09",
    "stock": 0,
    "created_at": null,
    "updated_at": null
  },
  {
    "id": 2,
    "bill": "97246",
    "type": 5,
    "amount": 150,
    "price": 118,
    "date": "2018-05-28",
    "stock": 1,
    "created_at": null,
    "updated_at": null
  }],
  "first_page_url": "http://site.test/purchases/get/list?page=1",
  "from": 1,
  "last_page": 25,
  "last_page_url": "http://site.test/purchases/get/list?page=25",
  "next_page_url": "http://site.test/purchases/get/list?page=2",
  "path": "http://site.test/purchases/get/list",
  "per_page": 2,
  "prev_page_url": null,
  "to": 2,
  "total": 49
}
```

**Comment by kenberkeley** [comment]
just write some convert function

**Comment by kenberkeley** [comment]
`query = { limit: 10, offset: 0, sort: '', order: '' }` by default

**Comment by joeljerushan** [comment]
@kenberkeley any suggestions ? or documentation for custom pagination urls for now `total` is working fine. its kinda server side pagination

**Comment by kenberkeley** [comment]
according to the *return view* you provided, `query.limit` is `per_page` which is `2`, `query.offset` is `(current_page - 1) * per_page` which is `0`, `total` is `49`

**Comment by joeljerushan** [comment]
that's fine but what about processing with next previous pages ?

**Comment by kenberkeley** [comment]
define `next previous pages`

**Comment by koskiszz** [comment]
And how I can filter data on server side?

**Comment by kenberkeley** [comment]
that's your business logic, pal

**Comment by joeljerushan** [comment]
@kenberkeley i'm confused about defining `next` `previous` pages can you show me documentation url or example here ?

**Comment by kenberkeley** [comment]
@joeljerushan : `that's fine but what about processing with next previous pages ?`

so i was confused what is `next previous pages`

**Comment by joeljerushan** [comment]
i was talking about ` "next_page_url": "http://site.test/purchases/get/list?page=2", ` server side processing to get next set of data and previous set of data.

Hope you understand

**Comment by kenberkeley** [comment]
control everything on the front end might be better

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/blob/master/examples/src/_mockData/index.js

**Comment by joeljerushan** [comment]
i understood ! but what if we get large set of data :) that will take time to load json object right

**Comment by kenberkeley** [comment]
so you got to make the pagination

**Comment by kenberkeley** [comment]
https://github.com/OneWayTech/vue2-datatable/issues/129#issuecomment-397866757

**Comment by joeljerushan** [comment]
Thank you :) link you posted helped me ;)

**Comment by alzambo** [comment]
Hi,
It seems that I cannot get the vue2-datatable pagination links working properly.

I'm a vue newbie and literally stucked on this test project since weeks... I cannot understand if it depends on vue or laravel side.

I'm sending to the rest api call these parameters:
````
methods: {
    getIncarichi() {
        axios.get("api/incarico2", {
            params: {
                limit: this.query.limit,
                offset: this.query.offset,
                sort: this.query.sort,
                order: this.query.order,
            }
        })
            .then(response => {
                this.data = response.data.data;
                this.total = response.data.total;
            })
            .catch(error => {
                console.log(error);
            });
    }
},
````

But the paginator is always setting up the page 1 response.
This is laravel code

````
public function index2(Request $request)
{
    $data = $this->model->getModel()
        ->orderBy($request->sort, $request->order)
        ->paginate($request->limit);
    return response()->json($data);
}
````

Example:
Clicking on the links (page 2 in this case) is always returning page 1 results using server-side laravel `LengthAwarePaginator`
![schermata 2018-10-27 alle 15 08 49](https://user-images.githubusercontent.com/10614142/47604449-49eb2a00-d9fa-11e8-847d-9b746837721e.png)

Here is the debug screenshot of $data object been builted
![schermata 2018-10-27 alle 15 08 39](https://user-images.githubusercontent.com/10614142/47604438-3344d300-d9fa-11e8-906a-95994e3dd8c4.png)

And the table isn't refreshed.
(Sorting and filtering are working correctly).

Could please someone point to the right direction?
Thank you,

Alex
