### ISSUE TITLE
Having Issues in IE 11

### ISSUE THREAD

**Issue by navedos** [OneWayTech/vue2-datatable#139]
Hello,

Hope this message finds you well. I have extensively used the datatables in my Vue JS projects but I have browser issues. The page is not getting loaded in IE because of issues while in other browsers it is working fine. Please can you provide your feedback. Thanks

![error](https://user-images.githubusercontent.com/41960837/43465067-86d7e3e4-94aa-11e8-83c6-afcb24ff54fc.png)

**Comment by kenberkeley** [comment]
more details?

**Comment by beargie** [comment]
@kenberkeley - I am also experiencing the same issue. I am using laravel-mix to compile assets with a vue frontend implementing this package.

The rendered code looks like this:
<img width="344" alt="screen shot 2018-08-23 at 11 20 53 am" src="https://user-images.githubusercontent.com/20710557/44535260-96974980-a6c7-11e8-9e9c-237c3ebfc090.png">

The error is that IE11 doesn't support the **_=>_** notation.

This appears to come from this file:
ROOT/node_modules/vue2-datatable-component/dist/min.js

I think that since the file is already minified, laravel-mix can't handle the babel conversion to make it IE11 compatible.

Suggestions to work around it?

**Comment by kenberkeley** [comment]
![img_1893](https://user-images.githubusercontent.com/13287948/44536055-2a9bfc00-a72e-11e8-8bcb-e01b8352012a.PNG)

**Comment by kenberkeley** [comment]
shown as above, the min.js is fine

**Comment by beargie** [comment]
@kenberkeley Thanks. I was able to update laravel-mix with the following rule that corrected the output to match what you posted.

In case it helps anyone else, add this to webpack.mix.js 
`if (mix.inProduction()) {

    mix.version();

    mix.webpackConfig({
        module: {
            rules: [{
                test: /\.jsx?$/,
                exclude: /node_modules(?!\/vue2-datatable-component)|dist/,
                use: [
                    {
                        loader: 'babel-loader',
                        options: Config.babel()
                    }
                ]
            }]
        }
    });
}`

**Comment by kenberkeley** [comment]
i havent used laravel so might not help u, sorry for that

**Comment by rebz** [comment]
@beargie - Thanks, this solved a big headache for me.

**Comment by mbcbus** [comment]
> @beargie - Thanks, this solved a big headache for me.
Good to hear @rebz, unfortunately this package has been deprecated so I wouldn't recommend any long term use unless @kenberkeley changes his mind for supporting it.

**Comment by rebz** [comment]
@mbcbus - Yep, primarily internal use on an internal platform that does not impact business objectives. Would love to see this rebuilt without jquery.
